### ISSUE TITLE
Setting up the integration fails

### ISSUE THREAD

**Issue by lukaszsobala** [HarvsG/ha-glinet4-integration#40]
![Screenshot_20250719-094816096 (1).png](https://github.com/user-attachments/assets/e90f1a7e-321c-4f03-bff9-a05ec01e477f)

Hello,

I have the settings set up as on the screen (so, non-default router IP). Creating the integration fails as shown.

**Comment by Chickenbreast0** [comment]
I got exactly the same issue.

I am currently on FW 4.8 RC2. Yesterday I was on RC1 and had the same issue.

**Comment by HarvsG** [comment]
Can you turn on debugging and paste the logs please?

**Comment by Chickenbreast0** [comment]
> Can you turn on debugging and paste the logs please?

Sure thing :) 

```text
2025-07-22 17:57:15.159 ERROR (MainThread) [custom_components.glinet.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/gli4py/glinet.py", line 123, in login
    res = await self._get_sid(username, hash)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gli4py/glinet.py", line 88, in _get_sid
    return await self._request(login_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/io/asyncio_strategy.py", line 32, in execute
    return await executable.execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/io/asyncio_strategy.py", line 21, in invoke
    response = await callback.on_success(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/io/asyncio_strategy.py", line 19, in invoke
    response = await callback.on_failure(type(error), error, tb)
                     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/io/execution.py", line 105, in on_failure
    return self._io.fail(exc_type, exc_val, exc_tb)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/io/interfaces.py", line 352, in fail
    compat.reraise(exc_type, exc_val, exc_tb)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/six.py", line 724, in reraise
    raise value
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/io/asyncio_strategy.py", line 16, in invoke
    response = await func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uplink/clients/aiohttp_.py", line 28, in new_callback
    response = callback(response)
  File "/usr/local/lib/python3.13/site-packages/uplink/builder.py", line 53, in wrapper
    return func(self._consumer, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uplink/hooks.py", line 22, in wrapper
    return hook(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/gli4py/error_handling.py", line 33, in raise_for_status
    raise NonZeroResponse("Request returned error code %s with message:' %s'. Full response %s" % (res['error']['code'], res['error']['message'],res))
gli4py.error_handling.NonZeroResponse: Request returned error code -32000 with message:' Access denied'. Full response {'id': 0, 'jsonrpc': '2.0', 'error': {'message': 'Access denied', 'code': -32000}}

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/glinet/config_flow.py", line 135, in async_step_user
    info = await validate_input(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/config_flow.py", line 104, in validate_input
    if not await hub.authenticate(data[CONF_PASSWORD]):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/config_flow.py", line 84, in authenticate
    await self.router.login(self.username, password)
  File "/usr/local/lib/python3.13/site-packages/gli4py/glinet.py", line 133, in login
    raise Exception("An unexpected error has occurred:", e)
Exception: ('An unexpected error has occurred:', NonZeroResponse("Request returned error code -32000 with message:' Access denied'. Full response {'id': 0, 'jsonrpc': '2.0', 'error': {'message': 'Access denied', 'code': -32000}}"))
```

**Comment by lukaszsobala** [comment]
My error happened on Flint 3. The password is the router admin password, not the WiFi password. The firmware version is 4.7.13.

**Comment by Chickenbreast0** [comment]
> In summary it looks as if `await self.router.login(self.username, password)` is failing because the GL.iNet is returning an access denies error. This is either because 1) the password sent is wrong, 2) the hash-generating process in gli4py is incorrect for your configuration or 3) some internal error in your box.
> 
> * [HarvsG/gli4py#3](https://github.com/HarvsG/gli4py/issues/3) seems to imply 2) might be the case - perhaps due to arecent firmware change
> * ~The error code `-32000` is reserved for for internal server errors so might imply 3) https://www.jsonrpc.org/specification#error_object~ when I test locally with an incorrect password I get the same error
> 
> 1. Can you please share what models of router you are using and their firmware versions.
> 2. Hopefully a stupid question, but please confirm that you are inputting the same password you use to log in to the GUI at `https://192.168.3.1` and NOT your wifi password.
> 3. Also please try restarting your router, I've seen a few errors like this, usually after repeated login attempts

There are no stupid questions :)

1. MT3000, FW: 4.8 RC2
2. Yes sure. My IP is 192.168.8.1
3. I did that. It was the same with the firmware version 4.8 RC1 as well as with RC2, which got released yesterday.

**Comment by HarvsG** [comment]
OK, I am currently testing on 4.3.25, so perhaps something has changed in more recent firmwares - which is worrying as GL-iNet no longer publicly document their API. Unfortunately, that means that the only way is painful reverse engineering.
You could try reaching out to them on the forum or by email to ask for example API authentication code

**Comment by HarvsG** [comment]
I contacted GL.iNet and they sent me a copy of the old authentication example code, I have sent a follow up.
In the meantime, this issue looks related it and may narrow it to 4.8+
https://github.com/angolo40/GLiNet_HomeAssistant/issues/8

**Comment by HarvsG** [comment]
OK, I raised this with GL.iNet and got nothing very helpful, they don't seem to think that much has changed on the login API

Those who are able, can you try running this script (with the IP and password changed) and see if authentication works
```python
import requests
import hashlib
from passlib.hash import md5_crypt, sha256_crypt, sha512_crypt

url = 'http://192.168.8.1/rpc' # CHANGE ME 
username = 'root'
password = 'goodlife'  # CHANGE ME 

try:
    # Step1: Get encryption parameters by challenge method
    challenge_data = {
        'jsonrpc': '2.0',
        'method': 'challenge',
        'params': {
            'username': username
        },
        'id': 0
    }


    response = requests.post(url, json=challenge_data)
    response.raise_for_status()
    result = response.json()['result']

    alg = result['alg']
    salt = result['salt']
    nonce = result['nonce']

    # Step2: Generate cipher text using openssl algorithm
    if alg == 1:  # MD5
        cipher_password = md5_crypt.using(salt=salt).hash(password)
    elif alg == 5:  # SHA-256
        cipher_password = sha256_crypt.using(salt=salt, rounds=5000).hash(password)
    elif alg == 6:  # SHA-512
        cipher_password = sha512_crypt.using(salt=salt, rounds=5000).hash(password)
    else:
        raise ValueError('Unsupported algorithm')

    # Step3: Generate hash values for login
    data = f"{username}:{cipher_password}:{nonce}"
    hash = hashlib.md5(data.encode()).hexdigest()

    # Step4: Get sid by login
    login_data = {
        'jsonrpc': '2.0',
        'method': 'login',
        'params': {
            'username': username,
            'hash': hash
        },
        'id': 0
    }

    response = requests.post(url, json=login_data)
    response.raise_for_status()
    result = response.json()['result']

    sid = result['sid']

    # Step5: Calling other APIs with sid
    system_status_data = {
        'jsonrpc': '2.0',
        'method': 'call',
        'params': [
          sid,
          'system',
          'get_status'
        ],
        'id': 0
    }

    response = requests.post(url, json=system_status_data)
    response.raise_for_status()
    print(response.json())

except requests.exceptions.RequestException as e:
    print("Request Exception:", e)
except (KeyError, ValueError) as e:
    print("Parameter Exception:", e)
except Exception as e:
    print("An error has occurred:", e)
```

If this works and my integration doesn't - which uses almost identical code - then maybe the problem is the call to the challenge endpoint that is used to confirm the GL.iNet router exists at the specified endpoint

**Comment by HarvsG** [comment]
> I get this:
> ```
> Parameter Exception: 'result'
> ```
 
Thank you, try it again but with
```
print(response.json())
result = response.json()['result']
```

**Comment by lukaszsobala** [comment]
the output:
```
{'id': 0, 'jsonrpc': '2.0', 'result': {'nonce': 'LjZ4iV15MXAVP9jQf0ab3WL4EuSm5H02', 'salt': 'YzDATzWwtLb7q/Hv', 'alg': 5, 'hash-method': 'sha256'}}
Parameter Exception: 'result'
```

**Comment by spusuf** [comment]
Same issue on Flint 3, firmware 4.7.14 (latest), router IP is 192.168.1.1 (changed from default .8.1), password has symbols in it and unsure if that's causing issues.

If I change the IP or change to https it changes to' Unexpected error'. But with correct http and IP it gives 'Invalid authentication'

**Comment by maillme** [comment]
I can't login either, same error - i'm on an AXT 1800 (Slate AX)

Not sure if it's relevant - but when I login via the admin page, there is no username.

**Comment by Admonstrator** [comment]
Great to hear that the answer from GL.iNet was helpful and a fix can be deployed now. 😃  🦭

**Comment by HarvsG** [comment]
<img width="1546" height="770" alt="Image" src="https://github.com/user-attachments/assets/23457e54-f722-4a1a-9c9b-7f66b5f0ba4c" />

Please download and test the new beta release via HACS.
Hopefully it should fix this issue, please report back with
1. Does it work on devices with firmware >=4.7.13
2. Does it break any devices with older firmware (I've tested it on my devices and it doesn't seem to)
3. Any changes with device discovery?

**Comment by daxharry** [comment]
Just tried but it looks like something is wrong : v0.1.3 was available in the integration tab once downloaded from HACS.

After forcing version v0.1.4b01 downloaed, it is indeed in custom_components/glinet, the manifest.json contains  "requirements": ["gli4py==0.0.13"], but it is not available in the HA integration tab.

Checking the logs as the issue may be on my side !

**Comment by daxharry** [comment]
Here the reason ;) 

2025-09-14 18:47:30.625 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'glinet' does not have a valid version key (0.1.4b01) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by elRadix** [comment]
Here with my flint 3, still not working
current firmware  v4.8.1 


`Logger: homeassistant.config_entries
Source: config_entries.py:751
First occurred: 19:14:22 (2 occurrences)
Last logged: 19:14:48

Error setting up entry GL-iNet BE9300 for glinet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/glinet/router.py", line 168, in setup
    await self.update_all()
  File "/config/custom_components/glinet/router.py", line 217, in update_all
    await self.update_device_trackers()
  File "/config/custom_components/glinet/router.py", line 344, in update_device_trackers
    device.update(dev_info)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/config/custom_components/glinet/router.py", line 572, in update
    self._if_type = list(DeviceInterfaceType)[
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dev_info["type"]
        ^^^^^^^^^^^^^^^^
    ]  # TODO be more index safe
    ^
IndexError: list index out of range

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:350
First occurred: 19:14:38 (1 occurrence)
Last logged: 19:14:38

Detected that custom integration 'glinet' sets option flow config_entry explicitly, which is deprecated at custom_components/glinet/config_flow.py, line 248: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/HarvsG/ha-glinet4-integration/issues`

**Comment by joolz1** [comment]
I can't even add GL iNet as a device as it doesn't show up after updating to 0.1.4b1

<img width="588" height="740" alt="Image" src="https://github.com/user-attachments/assets/e086777f-6d94-4520-9ae4-7c01554e4df8" />

**Comment by spusuf** [comment]
> I can't even add GL iNet as a device as it doesn't show up after updating to 0.1.4b1
> 
> <img alt="Image" width="588" height="740" src="https://private-user-images.githubusercontent.com/31555483/489317158-e086777f-6d94-4520-9ae4-7c01554e4df8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc4ODM2ODMsIm5iZiI6MTc1Nzg4MzM4MywicGF0aCI6Ii8zMTU1NTQ4My80ODkzMTcxNTgtZTA4Njc3N2YtNmQ5NC00NTIwLTlhZTQtN2MwMTU1NGU0ZGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTE0VDIwNTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYmI0NzY1NGFlZmM0ZWI0ZmZiNTc5Mjg1ZWE1Yzk1YWQ3NDcxMTEzNTIzZjJmMDRiMWUxMzAwZGEwMDUzZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pWZ-4xqguTkmy6U833lQCdiIaWNCOxR1A9WjfBZLkak">

You need to edit the manifest.json to remove the beta from the version number. Home assistant only supports x.x.x
After this it will be successfully loaded, have tested and it is working.

**Comment by lukaszsobala** [comment]
Where is this manifest.json? I just use the HACS webUI for installation. Is it after installing that one should edit this?

**Comment by joolz1** [comment]
> Where is this manifest.json? I just use the HACS webUI for installation. Is it after installing that one should edit this?

/homeassistant/config/custom_components/glinet/manifest.json

**Comment by lukaszsobala** [comment]
OK, I edited the manifest to 0.1.4 and encountered even more issues.
It seems that despite being version 0.1.4, the integration wants to "update" itself to 0.1.3. But when updating, actually, version 0.0.5 is installed.
Further, when I tried to set up the integration, it accepted the login but failed later. Here is the hass log:
```
[homeassistant.config_entries] Error setting up entry GL-iNet BE9300 for glinet

Traceback (most recent call last):

File "/home/homeassistant/.pyenv/versions/3.13.7/lib/python3.13/site-packages/homeassistant/config_entries.py", line 751, in __async_setup_with_context

result = await component.async_setup_entry(hass, self)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/mnt/dietpi_userdata/homeassistant/custom_components/glinet/__init__.py", line 26, in async_setup_entry

await router.setup()

File
"/mnt/dietpi_userdata/homeassistant/custom_components/glinet/router.py", line 168, in setup
    await self.update_all()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/glinet/router.py", line 217, in update_all
    await self.update_device_trackers()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/glinet/router.py", line 344, in update_device_trackers
    device.update(dev_info)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/mnt/dietpi_userdata/homeassistant/custom_components/glinet/router.py", line 572, in update
    self._if_type = list(DeviceInterfaceType)[
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dev_info["type"]
        ^^^^^^^^^^^^^^^^
    ]  # TODO be more index safe
    ^
IndexError: list index out of range

2025-09-15 01:13:30.557 WARNING (MainThread) [py.warnings] /home/homeassistant/.pyenv/versions/3.13.7/lib/python3.13/site-packages/paho/mqtt/matcher.py:57: RuntimeWarning: coroutine 'ClientSession.close' was never awaited

def iter_match(self, topic):

2025-09-15 01:13:30.558 ERROR
(MainThread) [homeassistant] Error doing job: Unclosed client session (None)

2025-09-15 01:13:30.559 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)

2025-09-15 01:13:30.566 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)

2025-09-15 01:13:30.567 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)

2025-09-15 01:13:33.324 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'glinet' sets option flow config_entry explicitly, which is deprecated at custom_components/glinet/config_flow.py, line 248: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/HarvsG/ha-glinet4-integration/issues
```
So, similar to errors reported above.

**Comment by lukaszsobala** [comment]
I have done just what you wrote and nothing changed, the integration fails to be set up, the logs are the same. Unclosed client session.

**Comment by HarvsG** [comment]
Closed as is fixed in 0.1.4

**Comment by lukaszsobala** [comment]
Thanks for creating the PR.
I cannot test the switches as I don't use a VPN or Tailscale (but I can say that the Tailscale switch is present and the VPN switch is absent).
